language: go

go:
  - 1.12.x
  - tip

git:
  depth: 1

install:
  - export GOPATH="$HOME/gopath"
  - go get -v -t -d github.com/jaztec/golife

script:
  - make fast-suite

after_success:
  - bash <(curl -s https://codecov.io/bash)